---
title: "MothurTest"
author: "Rebecca Furbeck"
date: "10/21/2021"
output: html_document
---

THINGS STILL BROKEN:
-tre names
-still mitchondria and chloroplast
-are the "unclassified" ones having problems aligning?
```{r}
library(ggplot2)
library(vegan) # ecological diversity analysis
library(dplyr)
library(scales) # scale functions for vizualizations
library(grid)
library(reshape2) # data manipulation package
library(cowplot)
library(phyloseq)
library(phytools)
```

Import
```{r}
sharedfile = "fullmerge.shared"
mothurlist = "fullmerge.list"
taxfile = "fullmerge.cons.taxonomy"
treefile <- "fullmerge.phylip.tre" 
mapfile = "DataListingsMeatandEnvONLY.xlsx - MappingFile.csv"
tree<-read.newick("patched.tre")
xtree<-phy_tree(tree)
# Import mothur data
mothur_data <- import_mothur(mothur_shared_file = sharedfile,
                             mothur_list_file = mothurlist,
                             #mothur_tree_file = treefile,
                             mothur_constaxonomy_file = taxfile)

#Achilles test
achi_data <- import_mothur(mothur_shared_file = "output.shared",
                             mothur_list_file = "output.list",
                            # mothur_tree_file = "patched.tre",
                             mothur_constaxonomy_file = "output.taxonomy")
```

Lets see who is there
```{r}
plot_bar(achi_data, fill="Rank2")
```

Normalize Because Wow 
```{r}
norm_mock <-  transform_sample_counts(achi_data, function(x) x / sum(x) )
#Use Top 50 Taxa for plots
top50 <- names(sort(taxa_sums(norm_mock), decreasing=TRUE))[1:50]
ps.top50 <- transform_sample_counts(norm_mock, function(OTU) OTU/sum(OTU))
ps.top50 <- prune_taxa(top50, ps.top50)

#Well this is overwhelming and disorganized
plot_bar(ps.top50, fill = "Rank3") 
```

Alpha Diversity
```{r}
alpha_meas = c("Observed", "Chao1", "ACE", "Shannon", "Simpson", "InvSimpson")

# plotting the alpha diversity estimators and color by time point
# adding plotting information to object "p"
p <- plot_richness(achi_data, measures=alpha_meas)

# plot data from "p" as a boxplot with ggplot2
p 

#plot rarefied data
p2 <- plot_richness(achi_scaled, measures=alpha_meas)
p2
```


Look at abundances of top 100
```{r}
topN <- 100
most_abundant_taxa = sort(taxa_sums(achi_data), TRUE)[1:topN]

#extract most_abundant_taxa from mouse_data
mouse_100_OTUs <- prune_taxa(names(most_abundant_taxa), achi_data)

# create a dataframe with the counts per otu
mouse_otu_sums <- data.frame(taxa_sums(mouse_100_OTUs))

# use the dataframe to plot the top 100 OTUs in a Rank abundance curve.
ggplot(mouse_otu_sums,aes(x=row.names(mouse_otu_sums), y=taxa_sums.mouse_100_OTUs.)) + 
  geom_bar(stat="identity",colour="black",fill="darkturquoise")  +
  xlab("OTU Rank") + ylab("Number of Sequences per OTU") +
  scale_x_discrete(expand = c(0,0)) + 
  scale_y_continuous(expand = c(0,0)) + theme_classic() +
  ggtitle("Rank Abundance Curve of the Top 100 OTUs") + 
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

Tree not working idk
```{r}
phy_tree("patched.tre")

plot_tree(phy_tree("patched.tre"), color=c("Rank3"))

```

Rarefy
```{r}
achi_scaled <- rarefy_even_depth(achi_data, sample.size = 2000, replace = FALSE, rngseed = 1)

```

PCA Beta Div
```{r}
mothur_pcoa <- ordinate(
  physeq = achi_scaled, 
  method = "PCoA", 
  distance = "bray"
)
```

Scree plot to check PCs
```{r}
plot_ordination(
  physeq = achi_scaled,
  ordination = mothur_pcoa,
  type="scree")
```

```{r}
plot_ordination(
  physeq = achi_scaled,
  ordination = mothur_pcoa,
  type="samples")
```

